server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/DC_Testing
spring.datasource.username=mercureit
spring.datasource.password=PFE2024


## Show or not log for each sql query
spring.jpa.show-sql = true
#
## Hibernate ddl auto (create, create-drop, update, none)
spring.jpa.hibernate.ddl-auto = update
#
## Naming strategy
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
#
## The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true
###-------------h2----------------
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=create
##spring.jpa.defer-datasource-initialization=true

### --------------MINIO---------------------------
minio.url=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucket=debt-collection
minio.access.key=minioadmin
minio.secret.key=minioadmin

logging.level.org.springframework.http.converter.json=DEBUG
logging.level.com.fasterxml.jackson.databind=DEBUG

##--------------keycloak config--------------
spring.security.oauth2.client.registration.keycloak.client-id=debt-collector-client
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/my_realm
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/my_realm

##--------------for debuging keycloak--------------
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.keycloak=DEBUG
logging.level.org.keycloak.adapters=DEBUG

# application.properties

# Gmail SMTP settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=assouli32@gmail.com
spring.mail.password=xlpplhustigmcaor


# Enable TLS settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
