package KieRule;
import testDrools.testDrools.model.Order;

rule "HDFC"
    when
        orderObject : Order(cardType == "HDFC", price > 10000);
    then
        System.out.println("discount to 20%");
        orderObject.setDiscount(201);
end
rule "ICICI"
    when
        orderObject : Order(cardType == "ICICI", price > 15000);
    then
        System.out.println("discount to 8%");
        orderObject.setDiscount(8);
end
rule "DBS"
    when
        orderObject : Order(cardType == "DBS", price > 15000);
    then
        System.out.println("discount to 20%");
        orderObject.setDiscount(15);
end
rule "DBS"
    when
        orderObject : Order(cardType == "DBS", price > 15000);
    then
        System.out.println("discount to 15%");
        orderObject.setDiscount(15);
end
rule "DBS"
    when
        orderObject : Order(cardType == "DBS", price > 15000);
    then
        System.out.println("discount to 15%");
        orderObject.setDiscount(15);
end 
